# Generated by Django 3.2.6 on 2021-08-27 12:50

import ckeditor.fields
from django.db import migrations, models
import help.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, upload_to=help.models.get_file_path)),
                ('title', models.CharField(max_length=1000)),
                ('title_ru', models.CharField(max_length=1000, null=True)),
                ('title_tr', models.CharField(max_length=1000, null=True)),
                ('title_en', models.CharField(max_length=1000, null=True)),
                ('title_zh_hans', models.CharField(max_length=1000, null=True)),
                ('text', ckeditor.fields.RichTextField(max_length=4000)),
                ('text_ru', ckeditor.fields.RichTextField(max_length=4000, null=True)),
                ('text_tr', ckeditor.fields.RichTextField(max_length=4000, null=True)),
                ('text_en', ckeditor.fields.RichTextField(max_length=4000, null=True)),
                ('text_zh_hans', ckeditor.fields.RichTextField(max_length=4000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('title_tr', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_zh_hans', models.CharField(max_length=200, null=True)),
                ('text', ckeditor.fields.RichTextField(max_length=4000)),
                ('text_ru', ckeditor.fields.RichTextField(max_length=4000, null=True)),
                ('text_tr', ckeditor.fields.RichTextField(max_length=4000, null=True)),
                ('text_en', ckeditor.fields.RichTextField(max_length=4000, null=True)),
                ('text_zh_hans', ckeditor.fields.RichTextField(max_length=4000, null=True)),
                ('goal', models.IntegerField()),
                ('raised', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Fond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('title_tr', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_zh_hans', models.CharField(max_length=200, null=True)),
                ('text', ckeditor.fields.RichTextField(max_length=4000)),
                ('text_ru', ckeditor.fields.RichTextField(max_length=4000, null=True)),
                ('text_tr', ckeditor.fields.RichTextField(max_length=4000, null=True)),
                ('text_en', ckeditor.fields.RichTextField(max_length=4000, null=True)),
                ('text_zh_hans', ckeditor.fields.RichTextField(max_length=4000, null=True)),
                ('goal', models.IntegerField()),
                ('raised', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Helping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, upload_to=help.models.get_file_path)),
                ('title', models.CharField(max_length=1000)),
                ('title_ru', models.CharField(max_length=1000, null=True)),
                ('title_tr', models.CharField(max_length=1000, null=True)),
                ('title_en', models.CharField(max_length=1000, null=True)),
                ('title_zh_hans', models.CharField(max_length=1000, null=True)),
                ('text', ckeditor.fields.RichTextField(max_length=4000)),
                ('text_ru', ckeditor.fields.RichTextField(max_length=4000, null=True)),
                ('text_tr', ckeditor.fields.RichTextField(max_length=4000, null=True)),
                ('text_en', ckeditor.fields.RichTextField(max_length=4000, null=True)),
                ('text_zh_hans', ckeditor.fields.RichTextField(max_length=4000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, upload_to=help.models.get_file_path)),
                ('title', models.CharField(max_length=1000)),
                ('title_ru', models.CharField(max_length=1000, null=True)),
                ('title_tr', models.CharField(max_length=1000, null=True)),
                ('title_en', models.CharField(max_length=1000, null=True)),
                ('title_zh_hans', models.CharField(max_length=1000, null=True)),
                ('text', ckeditor.fields.RichTextField(max_length=4000)),
                ('text_ru', ckeditor.fields.RichTextField(max_length=4000, null=True)),
                ('text_tr', ckeditor.fields.RichTextField(max_length=4000, null=True)),
                ('text_en', ckeditor.fields.RichTextField(max_length=4000, null=True)),
                ('text_zh_hans', ckeditor.fields.RichTextField(max_length=4000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('name_ru', models.CharField(max_length=1000, null=True)),
                ('name_tr', models.CharField(max_length=1000, null=True)),
                ('name_en', models.CharField(max_length=1000, null=True)),
                ('name_zh_hans', models.CharField(max_length=1000, null=True)),
                ('href', models.CharField(max_length=300)),
            ],
        ),
    ]
