# Generated by Django 3.2.6 on 2021-08-27 13:07

from django.db import migrations, models
import help.models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helping',
            name='icon',
            field=models.FileField(blank=True, upload_to=help.models.get_file_path),
        ),
    ]
