# Generated by Django 3.2.6 on 2021-08-27 13:15

from django.db import migrations, models
import help.models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_alter_helping_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='banner',
            field=models.ImageField(blank=True, upload_to=help.models.get_file_path),
        ),
        migrations.AddField(
            model_name='fond',
            name='banner',
            field=models.ImageField(blank=True, upload_to=help.models.get_file_path),
        ),
    ]
