# Generated by Django 3.2.6 on 2021-08-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0004_auto_20210827_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
