# Generated by Django 3.2.6 on 2021-09-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0005_menu_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='fond',
            name='initialRasised',
            field=models.IntegerField(default=0),
        ),
    ]
