# Generated by Django 3.2.6 on 2021-09-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0006_fond_initialrasised'),
    ]

    operations = [
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makeadonation', models.CharField(max_length=100)),
                ('aboutus', models.CharField(max_length=100)),
                ('discoverme', models.CharField(max_length=100)),
                ('helpingtoday', models.CharField(max_length=100)),
                ('howwehelppeople', models.CharField(max_length=100)),
                ('programs', models.CharField(max_length=100)),
                ('ourdonationprograms', models.CharField(max_length=100)),
                ('news', models.CharField(max_length=100)),
                ('latestblog', models.CharField(max_length=100)),
                ('footertext', models.CharField(max_length=100)),
                ('navigation', models.CharField(max_length=100)),
                ('contactus', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('support', models.CharField(max_length=100)),
                ('supporttext', models.CharField(max_length=100)),
                ('donate', models.CharField(max_length=100)),
                ('copyright', models.CharField(max_length=100)),
            ],
        ),
    ]
