# Generated by Django 3.2.6 on 2021-09-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0007_others'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='aboutus_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='aboutus_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='aboutus_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='aboutus_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='address_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='address_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='address_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='address_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='contactus_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='contactus_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='contactus_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='contactus_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='copyright_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='copyright_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='copyright_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='copyright_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='discoverme_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='discoverme_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='discoverme_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='discoverme_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='donate_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='donate_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='donate_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='donate_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='footertext_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='footertext_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='footertext_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='footertext_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='helpingtoday_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='helpingtoday_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='helpingtoday_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='helpingtoday_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='howwehelppeople_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='howwehelppeople_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='howwehelppeople_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='howwehelppeople_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='latestblog_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='latestblog_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='latestblog_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='latestblog_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='makeadonation_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='makeadonation_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='makeadonation_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='makeadonation_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='navigation_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='navigation_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='navigation_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='navigation_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='news_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='news_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='news_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='news_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='ourdonationprograms_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='ourdonationprograms_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='ourdonationprograms_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='ourdonationprograms_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='programs_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='programs_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='programs_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='programs_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='support_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='support_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='support_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='support_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='supporttext_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='supporttext_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='supporttext_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='supporttext_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
