# Generated by Django 3.2.6 on 2021-09-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0008_auto_20210901_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='others',
            name='goal',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='others',
            name='raised',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='others',
            name='readmore',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
