# Generated by Django 3.2.6 on 2021-09-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0009_auto_20210901_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='email_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='email_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='email_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='email_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='goal_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='goal_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='goal_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='goal_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='raised_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='raised_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='raised_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='raised_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='readmore_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='readmore_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='readmore_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='readmore_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
