# Generated by Django 3.2.6 on 2021-09-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0010_auto_20210901_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetailsOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogdetails', models.CharField(max_length=100)),
                ('blogdetails_ru', models.CharField(max_length=100, null=True)),
                ('blogdetails_tr', models.CharField(max_length=100, null=True)),
                ('blogdetails_en', models.CharField(max_length=100, null=True)),
                ('blogdetails_zh_hans', models.CharField(max_length=100, null=True)),
                ('newsletter', models.CharField(max_length=100)),
                ('newsletter_ru', models.CharField(max_length=100, null=True)),
                ('newsletter_tr', models.CharField(max_length=100, null=True)),
                ('newsletter_en', models.CharField(max_length=100, null=True)),
                ('newsletter_zh_hans', models.CharField(max_length=100, null=True)),
                ('enteremail', models.CharField(max_length=100)),
                ('enteremail_ru', models.CharField(max_length=100, null=True)),
                ('enteremail_tr', models.CharField(max_length=100, null=True)),
                ('enteremail_en', models.CharField(max_length=100, null=True)),
                ('enteremail_zh_hans', models.CharField(max_length=100, null=True)),
                ('subscribe', models.CharField(max_length=100)),
                ('subscribe_ru', models.CharField(max_length=100, null=True)),
                ('subscribe_tr', models.CharField(max_length=100, null=True)),
                ('subscribe_en', models.CharField(max_length=100, null=True)),
                ('subscribe_zh_hans', models.CharField(max_length=100, null=True)),
                ('recentposts', models.CharField(max_length=100)),
                ('recentposts_ru', models.CharField(max_length=100, null=True)),
                ('recentposts_tr', models.CharField(max_length=100, null=True)),
                ('recentposts_en', models.CharField(max_length=100, null=True)),
                ('recentposts_zh_hans', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
