# Generated by Django 3.2.6 on 2021-09-03 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0011_blogdetailsother'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=1000)),
                ('fond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help.fond')),
            ],
        ),
    ]
