# Generated by Django 3.2.6 on 2021-09-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0012_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='conversationId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payments',
            name='message',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='payments',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
