# Generated by Django 3.2.6 on 2021-09-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0013_auto_20210903_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='conversationId',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
